language: python
sudo: true
dist: trusty
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy"
  - "pypy3"

env:
  - RL=30
  - RL=31
  - RL=32
  - RL=33
  - RL=34
  - RL=35
  - RL=36

matrix:
  fast_finish: true
  allow_failures:
    - python: "3.8"
    - python: "pypy3"
  include:
    - stage: build docker image
      script:
        - docker login -u="27658520" -p="$sabushandyoliver29"
        - docker build -t testrenderv2 .
        - - docker images
        - docker tag testrenderv2 27658520/testrenderv2
        - docker push 27658520/testrenderv2
    - stage: test
      script: docker run --rm 27658520/testrenderv2
    - script: docker run --rm 27658520/testrenderv2

before_install:
  - sudo apt-get update
  - sudo apt-get install -y imagemagick
  - sudo apt-get install -y ghostscript
  #- sudo sed -i 's#<policy domain="coder" rights="none" pattern="PDF" />#<policy domain="coder" rights="read|write" pattern="PDF" />#' /etc/ImageMagick-6/policy.xml

install:
  - TOX_ENV=py${TRAVIS_PYTHON_VERSION}-rl${RL}
  - pip install tox coveralls Sphinx sphinx-rtd-theme nose

script: tox -e $TOX_ENV
after_success: coveralls $COVERALLS_OPTION

notifications:
  irc: "chat.freenode.net#xhtml2pdf"

before_script:
  - cd doc/source ; sphinx-build -nW -b html -d _build/doctrees . _build/html ; cd ../..
